how alphabet: user.help_alphabet(user.get_alphabet())
how context$: user.help_context()
how active$: user.help_context_enabled()
how refresh$: user.help_refresh()
how next$: user.help_next()
how previous$: user.help_previous()
how context <user.help_contexts>$: user.help_selected_context(user.help_contexts)
how <user.help_context_index>$: user.help_select_index(help_context_index)
how return$: user.help_return()
how close$: user.help_hide()

