#!/bin/zsh

protocol=$1
user=$2
repo=$3

if [[ "$user" == *"/"* ]]
then
  echo "detected '/', splitting..."
  repo_path=$user
  user=$(echo $repo_path | grep -oE "^[^/]+")
  repo=$(echo $repo_path | grep -oE  "[^/]+$")
  echo "user: " $user
  echo "repo: " $repo
fi

base=$HOME/git
site=''
strat=$protocol

case $protocol in
  github | gh)
    strat=github
    site=github
    ;;
  exp)
    strat=github
    site=github
    repo=exp-$2
    user=towc
    ;;
  freedesktop | fd)
    start=freedesktop
    site=freedesktop
    ;;
  vps)
    strat=vps
    base=$HOME/work/vps/git
    site='bitbucket'
    ;;
  *)
    echo "Protocol $site not found, exiting"
    exit 1
esac

cd $base

echo "trying to use $base/$site/$user/$repo"

if [ ! -d $site ]
then
  echo "creating $base/$site directory"
  mkdir $site
fi

cd $site

if [ ! -d $user ]
then
  echo "creating $base/$site/$user"
  mkdir $user
fi

cd $user

case $strat in
  github)
    git clone git@github.com:$user/$repo
    ;;
  freedesktop)
    git clone https://gitlab.freedesktop.org/$user/$repo.git
    # git clone git@ssh.gitlab.freedesktop.org:$user/$repo.git
    ;;
  vps)
    git clone ssh://git@dev.viewpointsystem.io:7999/$user/$repo.git
    ;;
esac

dir=$base/$site/$user/$repo

echo "repo is in $dir"

# for easy cdl
echo $dir > /tmp/.tmux-last-cd
